/*
 * MainFrame.java
 *
 * 
 */

package xklusac.extensions;

import java.util.Date;
import java.util.LinkedList;

/**
 * Class MainFrame<p>This class generates the Main Frame of application that contains buttons for graph export into bitmap files (jpg, png, gif, bmp).<br>
 * Also, when this frame's [x] close button is clicked, whole simulation is terminated immediately.<br>
 * To run the simulation with visualization, Java 1.6 or newer is needed.
 * @author  Dalibor Klusacek
 */
public class MainFrame extends javax.swing.JFrame {
LinkedList<Visualizator> ia = null;
    /** Creates new form MainFrame */
    public MainFrame(LinkedList<Visualizator> ia) {
        initComponents();
        this.ia = ia;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alea 4.0");

        jLabel1.setText("Save graphs to");

        jButton1.setText("png");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jpg");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("bmp");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("gif");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("Alea 4.0");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitHandler(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Quit application.
 *
 */
private void exitHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitHandler
System.exit(1);// TODO add your handling code here:
}//GEN-LAST:event_exitHandler

/**
 * Save graphs to png.
 *
 */

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String ext = "png"; // jpg, png, bmp (j2se 1.5+), gif (j2se 1.6+)
Date d = new Date();
String identifier = ""+d.getTime();
//ext="-"+123+"."+ext;
    for(int im = 0; im < ia.size(); im++){
    Visualizator iaw = ia.get(im);
    
    iaw.saveToFile3(ext, identifier);
}
}//GEN-LAST:event_jButton1ActionPerformed

/**
 * Save graphs to jpg.
 *
 */

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String ext = "jpg"; // jpg, png, bmp (j2se 1.5+), gif (j2se 1.6+)
Date d = new Date();
String identifier = ""+d.getTime();

    for(int im = 0; im < ia.size(); im++){
    Visualizator iaw = ia.get(im);
    
    iaw.saveToFile3(ext, identifier);
}
}//GEN-LAST:event_jButton2ActionPerformed

/**
 * Save graphs to bmp.
 *
 */

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String ext = "bmp"; // jpg, png, bmp (j2se 1.5+), gif (j2se 1.6+)
Date d = new Date();
String identifier = ""+d.getTime();

    for(int im = 0; im < ia.size(); im++){
    Visualizator iaw = ia.get(im);
    
    iaw.saveToFile3(ext, identifier);
}
}//GEN-LAST:event_jButton3ActionPerformed


/**
 * Save graphs to gif.
 *
 */

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String ext = "gif"; // jpg, png, bmp (j2se 1.5+), gif (j2se 1.6+)
Date d = new Date();
String identifier = ""+d.getTime();

    for(int im = 0; im < ia.size(); im++){
    Visualizator iaw = ia.get(im);
    
    iaw.saveToFile3(ext, identifier);
}

}//GEN-LAST:event_jButton4ActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

}
